CMS_HOST: studio.local.overhang.io
CMS_OAUTH2_SECRET: gjobE0yA3gwMmXizWimOP0oK
CONTACT_EMAIL: contact@local.overhang.io
ENABLE_HTTPS: false
ID: okvrofMDk4mlQrc85iQtZpZL
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEowIBAAKCAQEAsoPAOwERyBrqH440tpvFRc8QW1WKVnEp0+3DJx6GSJanrafy

  /xIvZiIkDVQQZ6tXziXe7/TOZfNuQf7XE6rz16o5Oa50TXHGZBBGe+lT9w4YickB

  msJnkmDjONjAaBMFmgLLaH0tQKw9vb2iwDdp6bh9XH0hCvJLET/LaWmLc1uEsTw3

  mMDWJ/pR9ewOZHb28mbw+5CziUvg4qD7gaS5xm8mtvIqskIoNrfBJJJ/+FHKmvqD

  Oi+sCUpaWIWgtwIdyMolaxlVSn+JOpuPIHjvbSu2SGbbNkx9ExUdkHxXSR7lP0RY

  lDo6QnddkLa+uFhILO+ZK/WnB4YZuxjq35o+TwIDAQABAoIBABbxWDfdHn1teXCT

  yhI8Doxhx97igrSIYman6fXG9l2G60b7d6oGRXbmurkceD1H/VwebDrCZ50dE6sX

  XGoH2xijz9X/e1gRYCeFG0yamMgplMgZ6thf1Ygvu+mW8JI6UPUnGHW153vRMeAx

  v/ncmq1HS5P4Sv0JVdIs35uNIoyGhmPVuYJhQSirOCM2+g61xX0X2sZnueWPW7IJ

  V2flF71njD7O2sWXHgj5YCoFlacE2CbYReOFaTNuxGm/4gMnI9r2vs9QpHxHVNDW

  Fmb0T1IaTCz5h1ajlnQe+Nw/Z/rzl08mqKSJLnMaFql7SJSLucu4mj2BkYS1pE8V

  yJg8ZjECgYEAvTjPzH21SJJI9wGzAOvinjqtMt+mIBwPSVpunmpkpTr8PGFCn+kN

  IvM9lFrL8jkJiHubeCrrT/DCmZYrOLgBcVTWZveAJIicpFp98g7fpLaUfcJrXXZq

  /qqPpp7RuX3HGUggzNobRP4/MFAFfmYIL068WAXz9rBBMbkDqkW5pD8CgYEA8YOY

  QCqebxO1T/VmUMl/V/eOjBapyv4ew1PJdkPETatmI/SGSRY86LDbNl2C3fKXfoTa

  RZvmLGcmODh6masSOxJVxSV9BYzcMxP9hVSA+UQlKl84JGcMOCHK7gEQFqnrAVGq

  xejciIpBVRi3Y42JHDPnLjhYRO03T0YGaOW1ofECgYB06puK8MmIk8q9xLEECrw1

  pG/MFWCiSnQvkM701yxk47Ni4321LNzPEZilCA0oF5IKYMXJVEudU1gKaj0+iINr

  sU3gxWDKMhcHflp/rC0Hq0DJC84nK7okrOKhw1Q21r6komqR6NocoTQN+APM++Jm

  yLGbeeIqNPGzdWwMU5THJQKBgQDa2a+OfdBBwW8sfKhxjpXppbezdBn6i1pfD77g

  fzoUU7vj2wIQmqkpBpIuaoBbFSh4inSsXUAvfm0gxvU56M5FXzD/zB/FdsZXNscm

  GdQhjMHM6qoaOpLVDrIwCCCHGQSOlm2Ul5W32Oio7xPHj4ruVo4n0QETvI3BNSg7

  x+RWUQKBgAy8WZQjwi28ACwKdUdxO3ywlWmAMEyuvkVZywiPcPdfbnlCKQSuSfUx

  lgH5PpU1m/+YAc1TaTtcX1u63L3bOlyKDD4boTyBMssXGGv9w1gvy/J9CnG8Pc9E

  wfantT2Z1CdxgxhYtbzsBXGDFyvxAaS01tN0jsP3oPjsTpiLzgse

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: LRgc9TlX
OPENEDX_MYSQL_PASSWORD: cjDWPZI5
OPENEDX_SECRET_KEY: CuDKY01NrROV9UABE28uIXbS
PLATFORM_NAME: My Open edX
PLUGINS:
- mfe
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
